---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r}
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyr)
library(readr)
library(lubridate)
library(forcats)
library(DT)
library(plotly)
library(scales)
```


```{r}

seasons_all <- read_tsv("master_season1-35.tsv")
seasons_all_clean <- seasons_all %>% 
  separate(air_date, sep="-", into = c("year", "month", "day")) %>% 
  select(-comments, -notes) %>% 
  mutate(category = str_to_lower(string = category),
         answer = str_to_lower(string = answer),
         question = str_to_lower(string = question)) %>% 
  filter(year != "2019")
```

```{r}
# Create lists of gods
greek_gods <- c("athena", "zeus", "poseidon", "hades", "hera", "apollo", "demeter", "artemis", "aphrodite", "ares")
norse_gods <- c("odin", "loki", "thor", "njord", "heimdall", "frigg", "tyr", "baldur", "idun", "bragi")
hindu_gods <- c("vishnu", "brahma", "shiva", "lakshmi", "hanuman", "ganesha", "krishna", "kali", "rama", "saraswati")

# Create filtered datasets for each type of god
seasons_all_greek <- seasons_all_clean %>% 
  filter(str_detect(question, greek_gods) | str_detect(answer, greek_gods))

seasons_all_norse <- seasons_all_clean %>% 
  filter(str_detect(question, norse_gods) | str_detect(answer, norse_gods))

seasons_all_hindu <- seasons_all_clean %>% 
  filter(str_detect(question, hindu_gods) | str_detect(answer, hindu_gods))

# Merge all 3 dataframes
seasons_all_gods <- merge(merge(seasons_all_greek, seasons_all_norse, all = TRUE), seasons_all_hindu, all = TRUE)
```


```{r}
seasons_all_gods_cat <- seasons_all_gods %>% 
  group_by(category) %>% 
  count()

seasons_all_gods_top5 <- seasons_all_gods_cat %>%
    filter(category == "authors" |
         category == "books & authors" |
         category == "literature" | 
         category == "mythology" | 
         category == "english literature")
```


```{r}
seasons_all_gods_athenaQ <- seasons_all_gods %>% 
  mutate(god_name = stringr::str_extract(question, "athena"))

seasons_all_gods_athenaA <- seasons_all_gods %>% 
  mutate(god_name = stringr::str_extract(answer, "athena"))

seasons_all_gods_zeusQ <- seasons_all_gods %>% 
  mutate(god_name = stringr::str_extract(question, "zeus"))

seasons_all_gods_zeusA <- seasons_all_gods %>% 
  mutate(god_name = stringr::str_extract(answer, "zeus"))

seasons_all_gods_ZA <- merge(merge(merge(seasons_all_gods_athenaQ, seasons_all_gods_athenaA, all = TRUE), seasons_all_gods_zeusQ, all = TRUE), seasons_all_gods_zeusA, all = TRUE)
```

```{r}
# Relevel and change NA to other
seasons_all_gods_ZA_group <- seasons_all_gods_ZA %>% 
  group_by(category, year, god_name) %>% 
  count()

seasons_all_gods_ZA_group$god_name <- as.character(seasons_all_gods_ZA_group$god_name)
seasons_all_gods_ZA_group$god_name[is.na(seasons_all_gods_ZA_group$god_name)] <- "other"
seasons_all_gods_ZA_group$god_name <- as.factor(seasons_all_gods_ZA_group$god_name)
seasons_all_gods_ZA_group$god_name <- relevel(seasons_all_gods_ZA_group$god_name, "other")

color_pal <- c("grey75", "tomato1", "royalblue1")
```


```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Top category in Jeopardy

```{r}
### Top five categories of 
  
cat_pro <- seasons_all_clean %>%
  mutate(category = fct_lump(category, n=5)) %>% # Making lumpsum
  group_by(year, category) %>%
  summarise(count = n())%>%
  mutate(freq= count/sum(count)*100) %>%
  filter(category!="Other") %>% #removed Other because of large proportion
  ggplot()+
  geom_bar(aes(x = year, y= freq, fill= category), stat="identity")+
  theme(axis.text.x = element_text(angle = 45))+
  scale_x_discrete(breaks = seq(1984, 2018, 4))+
  #scale_y_continuous(labels=percent)+
  labs(x = "Year", y = "Proportion (%)") +
  theme_classic() +
  ggtitle("Proportion of questions asked from the top five \ncategories by season")

cat_pro <- ggplotly(cat_pro) 

cat_pro
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
sea_98<- seasons_all_clean %>%
  mutate(b_logi = year<1998,
         a_logi = year>=1998) %>%
  group_by(category)%>%
  summarise(before_98= sum(b_logi),
            after_98=sum(a_logi)) %>%
  arrange(desc(before_98)) %>%
  head(n=50)
datatable(sea_98)
```

### Chart C

```{r}
god<-seasons_all_gods_ZA_group %>% 
  ggplot(aes(x = year, y = n, fill = god_name)) +
  scale_fill_manual(values = color_pal) +
  geom_bar(position = "stack", stat = "identity") +
  theme_classic() +
  ggtitle("The prevalence of Zeus and Athena over time") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Year", y = "Number of mentions", fill = "God Name")+
    scale_x_discrete(breaks = seq(1984, 2018, 4))
ggplotly(god)

```

